# Uses ${SERVER_ROOT} for all volumes. Requires a .env file in the same directory with SERVER_ROOT, PUID, PGID, and TZ set.
version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400

  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ${SERVER_ROOT}/config/nextcloud:/config
      - ${SERVER_ROOT}/downloads:/data

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
      - "8920:8920"
    environment:
      - TZ=${TZ}
    volumes:
      - ${SERVER_ROOT}/config/jellyfin:/config
      - ${SERVER_ROOT}/media:/media
      - ${SERVER_ROOT}/downloads/qbittorrent:/downloads

  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    environment:
      - TZ=${TZ}
    volumes:
      - ${SERVER_ROOT}/config/pihole/etc-pihole:/etc/pihole
      - ${SERVER_ROOT}/config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ${SERVER_ROOT}/config/homeassistant:/config

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SERVER_ROOT}/config/sonarr:/config
      - ${SERVER_ROOT}/downloads/qbittorrent/tv-sonarr:/downloads/tv-sonarr
      - ${SERVER_ROOT}/media/tv:/tv

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SERVER_ROOT}/config/radarr:/config
      - ${SERVER_ROOT}/downloads/qbittorrent/radarr:/downloads/radarr
      - ${SERVER_ROOT}/media/movies:/movies

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SERVER_ROOT}/config/jackett:/config
      - ${SERVER_ROOT}/downloads:/downloads

  organizr:
    image: organizr/organizr
    container_name: organizr
    restart: unless-stopped
    ports:
      - 9980:80
    volumes:
      - ${SERVER_ROOT}/config/organizr:/config

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8081
    volumes:
      - ${SERVER_ROOT}/config/qbittorrent:/config
      - ${SERVER_ROOT}/downloads/qbittorrent:/downloads
